version = 1

exclude_patterns = [ "examples/**", "docs/**" ]
test_patterns = [ "**/test/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "es-modules"
  environment = ["nodejs"]
  dialect = "typescript"
  dependency_file_paths = [ 
    "packages/rtm-api/package.json",
    "packages/webhook/package.json", 
    "packages/types/package.json", 
    "packages/web-api/package.json",
    "packages/oauth/package.json",
    "packages/logger/package.json",
    "packages/interactive-messages/package.json",
    "packages/events-api/package.json",
    "packages/client/package.json" ]
